//! Local (no API calls) commit message generator.
//!
//! Analyses the staged file statuses and diffs to produce a conventional-commit
//! style message like `feat(TeamCode): update 3 file(s)`.

use crate::diff::FileDiff;
use crate::status::{FileStatus, GitStatus, StatusKind};

// ── CommitMessageBuilder ──────────────────────────────────────────────────────

pub struct CommitMessageBuilder;

impl CommitMessageBuilder {
    /// Build a full commit message from the given status and diffs.
    ///
    /// Format:
    /// ```text
    /// {prefix}({scope}): update {N} file(s)
    ///
    /// - path/to/file.java  +10 -3
    /// - another/file.java  +0 -5
    ///
    /// Generated by Alloy Studio
    /// ```
    pub fn build(status: &GitStatus, diffs: &[FileDiff]) -> String {
        let prefix = Self::suggest_prefix(status);
        let scope = Self::suggest_scope(status);

        let staged: Vec<&FileStatus> = status.staged().collect();
        let file_count = staged.len().max(1);

        // Summary line.
        let summary = if let Some(scope) = scope {
            format!("{prefix}({scope}): update {file_count} file(s)")
        } else {
            format!("{prefix}: update {file_count} file(s)")
        };

        // Build body: list each staged file with its diff stats.
        let mut body = String::new();
        for fs in &staged {
            let (adds, dels) = diff_stats_for(fs, diffs);
            body.push_str(&format!("- {}  +{adds} -{dels}\n", fs.path));
        }

        // If no staged files listed, fall back to unstaged+untracked.
        if body.is_empty() {
            for fs in status.files() {
                let (adds, dels) = diff_stats_for(fs, diffs);
                body.push_str(&format!("- {}  +{adds} -{dels}\n", fs.path));
            }
        }

        if body.is_empty() {
            format!("{summary}\n\nGenerated by Alloy Studio\n")
        } else {
            format!("{summary}\n\n{body}\nGenerated by Alloy Studio\n")
        }
    }

    /// Choose a conventional-commit prefix based on the file statuses.
    ///
    /// Rules (first match wins):
    /// * Any path contains `fix`, `bug`, `patch`, or `issue` → `"fix"`
    /// * All changed files are newly added → `"feat"`
    /// * More deletions than additions across all diffs → `"refactor"`
    /// * Otherwise → `"chore"`
    pub fn suggest_prefix(status: &GitStatus) -> &'static str {
        let files = status.files();

        // Check path keywords for bug-fix indicators.
        for fs in files {
            let lower = fs.path.to_lowercase();
            if lower.contains("fix")
                || lower.contains("bug")
                || lower.contains("patch")
                || lower.contains("issue")
            {
                return "fix";
            }
        }

        // All new/added → feature.
        let all_new = !files.is_empty()
            && files
                .iter()
                .all(|f| matches!(f.kind, StatusKind::Added | StatusKind::Untracked));
        if all_new {
            return "feat";
        }

        // Heavy removals → refactor.
        let total_adds: u32 = files.iter().map(|f| f.additions).sum();
        let total_dels: u32 = files.iter().map(|f| f.deletions).sum();
        if total_dels > total_adds && total_dels > 0 {
            return "refactor";
        }

        "chore"
    }

    /// Suggest a scope string from the common directory prefix of all staged files.
    ///
    /// Returns `None` if there is no common non-trivial directory.
    pub fn suggest_scope(status: &GitStatus) -> Option<String> {
        let staged: Vec<&FileStatus> = status.staged().collect();
        let files: &[&FileStatus] = if staged.is_empty() {
            &status.files().iter().collect::<Vec<_>>()
        } else {
            &staged
        };

        if files.is_empty() {
            return None;
        }

        // Collect the first path component (top-level directory) of each file.
        let dirs: Vec<&str> = files
            .iter()
            .filter_map(|f| {
                let p = std::path::Path::new(&f.path);
                p.components().next().and_then(|c| {
                    // Only use directory components, not file names at the root.
                    if p.components().count() > 1 {
                        c.as_os_str().to_str()
                    } else {
                        None
                    }
                })
            })
            .collect();

        if dirs.is_empty() {
            return None;
        }

        // Check whether all dirs agree on the same first component.
        let first = dirs[0];
        if dirs.iter().all(|d| *d == first) {
            Some(first.to_string())
        } else {
            None
        }
    }
}

// ── helper ────────────────────────────────────────────────────────────────────

fn diff_stats_for(fs: &FileStatus, diffs: &[FileDiff]) -> (u32, u32) {
    // Try to find matching diff entry.
    for diff in diffs {
        if diff.path == fs.path || diff.old_path.as_deref() == Some(&fs.path) {
            return (diff.additions, diff.deletions);
        }
    }
    // Fall back to pre-computed stats on the FileStatus.
    (fs.additions, fs.deletions)
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diff::FileDiff;
    use crate::status::{FileStatus, GitStatus, StatusKind};

    fn make_status(files: Vec<FileStatus>) -> GitStatus {
        GitStatus(files)
    }

    fn make_file_status(path: &str, kind: StatusKind, staged: bool, adds: u32, dels: u32) -> FileStatus {
        FileStatus {
            path: path.to_string(),
            old_path: None,
            kind,
            staged,
            additions: adds,
            deletions: dels,
        }
    }

    fn make_diff(path: &str, adds: u32, dels: u32) -> FileDiff {
        FileDiff {
            path: path.to_string(),
            old_path: None,
            hunks: vec![],
            is_binary: false,
            additions: adds,
            deletions: dels,
        }
    }

    // --- suggest_prefix -------------------------------------------------------

    #[test]
    fn prefix_fix_when_path_contains_fix() {
        let status = make_status(vec![make_file_status(
            "src/fix_motor.java",
            StatusKind::Modified,
            true,
            5,
            2,
        )]);
        assert_eq!(CommitMessageBuilder::suggest_prefix(&status), "fix");
    }

    #[test]
    fn prefix_fix_when_path_contains_bug() {
        let status = make_status(vec![make_file_status(
            "src/bugfix/Motor.java",
            StatusKind::Modified,
            true,
            1,
            1,
        )]);
        assert_eq!(CommitMessageBuilder::suggest_prefix(&status), "fix");
    }

    #[test]
    fn prefix_feat_when_all_new() {
        let status = make_status(vec![
            make_file_status("TeamCode/NewOpMode.java", StatusKind::Added, true, 50, 0),
            make_file_status("TeamCode/Helper.java", StatusKind::Added, true, 20, 0),
        ]);
        assert_eq!(CommitMessageBuilder::suggest_prefix(&status), "feat");
    }

    #[test]
    fn prefix_refactor_when_heavy_deletions() {
        let status = make_status(vec![make_file_status(
            "src/OldCode.java",
            StatusKind::Modified,
            true,
            5,
            100,
        )]);
        assert_eq!(CommitMessageBuilder::suggest_prefix(&status), "refactor");
    }

    #[test]
    fn prefix_chore_default() {
        let status = make_status(vec![make_file_status(
            "README.md",
            StatusKind::Modified,
            true,
            3,
            3,
        )]);
        assert_eq!(CommitMessageBuilder::suggest_prefix(&status), "chore");
    }

    // --- suggest_scope --------------------------------------------------------

    #[test]
    fn scope_common_directory() {
        let status = make_status(vec![
            make_file_status("TeamCode/OpMode.java", StatusKind::Modified, true, 1, 0),
            make_file_status("TeamCode/Helper.java", StatusKind::Modified, true, 2, 0),
        ]);
        assert_eq!(
            CommitMessageBuilder::suggest_scope(&status),
            Some("TeamCode".to_string())
        );
    }

    #[test]
    fn scope_none_when_different_directories() {
        let status = make_status(vec![
            make_file_status("TeamCode/A.java", StatusKind::Modified, true, 1, 0),
            make_file_status("FtcRobotController/B.java", StatusKind::Modified, true, 2, 0),
        ]);
        assert_eq!(CommitMessageBuilder::suggest_scope(&status), None);
    }

    #[test]
    fn scope_none_for_root_files() {
        let status = make_status(vec![make_file_status(
            "build.gradle",
            StatusKind::Modified,
            true,
            1,
            0,
        )]);
        assert_eq!(CommitMessageBuilder::suggest_scope(&status), None);
    }

    // --- build ----------------------------------------------------------------

    #[test]
    fn build_contains_summary_and_footer() {
        let status = make_status(vec![make_file_status(
            "TeamCode/OpMode.java",
            StatusKind::Modified,
            true,
            5,
            2,
        )]);
        let diffs = vec![make_diff("TeamCode/OpMode.java", 5, 2)];
        let msg = CommitMessageBuilder::build(&status, &diffs);
        assert!(msg.contains("Generated by Alloy Studio"));
        assert!(msg.contains("TeamCode/OpMode.java"));
    }

    #[test]
    fn build_includes_diff_stats() {
        let status = make_status(vec![make_file_status(
            "TeamCode/OpMode.java",
            StatusKind::Modified,
            true,
            10,
            3,
        )]);
        let diffs = vec![make_diff("TeamCode/OpMode.java", 10, 3)];
        let msg = CommitMessageBuilder::build(&status, &diffs);
        assert!(msg.contains("+10"));
        assert!(msg.contains("-3"));
    }

    #[test]
    fn build_uses_scope_in_summary() {
        let status = make_status(vec![
            make_file_status("TeamCode/A.java", StatusKind::Modified, true, 1, 0),
            make_file_status("TeamCode/B.java", StatusKind::Modified, true, 1, 0),
        ]);
        let msg = CommitMessageBuilder::build(&status, &[]);
        assert!(msg.contains("(TeamCode)"));
    }

    #[test]
    fn build_empty_status_still_produces_message() {
        let status = make_status(vec![]);
        let msg = CommitMessageBuilder::build(&status, &[]);
        assert!(msg.contains("Generated by Alloy Studio"));
    }
}
